### ISSUE TITLE
Search throws DeprecatedWrapperException when returns multiple pages

### ISSUE THREAD

**Issue by Balint1** [PoLaKoSz/Ncore#1]
### Description of Issue

Searching for any term which gives a result of more than one pages throws DeprecatedWrapperException.
This is probably because next/previous page href link also contains the query params "tipus", "mire" and "miben".
So the 93th line of SearchParser cannot parse the value:
![image](https://user-images.githubusercontent.com/17236185/104073416-ee3d9d80-520d-11eb-9adc-35d0d06b4cc4.png)

### Steps to Reproduce the Issue
To reproduce this issue,we can just run the sample project in the repository. Searching for "Inna" will throw an error:
![image](https://user-images.githubusercontent.com/17236185/104073709-ad925400-520e-11eb-863a-00e01a6aa8f3.png)

### Expected Outcomes
- The SearchParser can correctly parse the next/previous href links.

**Comment by PoLaKoSz** [comment]
Thank You for the details and the PR too. I pushed a commit to your branch with a test case to validate the fix and released `v1.1.1` on NuGet too which contains your fix.
Thanks again!

**Comment by Balint1** [comment]
No problem! Thanks for the awesome library, that's exactly what I needed for my raspberry.
